// ─── Master Tool Routes — used by DropZone, ToolGrid, CommandPalette ─────────
// Each tool entry declares: which MIME types it accepts for file-drop routing,
// which action verbs it supports, and keywords for fuzzy search.

export const WORKSPACE_TOOLS = [
  {
    slug: '/pdf-tools',
    name: 'PDF Converter, Merger & Splitter',
    navLabel: 'PDF Tools',
    icon: '📄',
    category: 'PDF Tools',
    color: '#f97316',
    accepts: ['application/pdf', 'image/jpeg', 'image/png', 'image/webp'],
    actions: ['Merge', 'Split', 'Convert'],
    tabs: { merge: 'merge', split: 'split', convert: 'convert' },
    keywords: ['pdf', 'merge', 'split', 'convert', 'combine', 'extract', 'pages', 'document'],
  },
  {
    slug: '/image-resizer',
    name: 'Image Compressor & Resizer',
    navLabel: 'Image Resizer',
    icon: '🗜️',
    category: 'Design & Photography',
    color: '#8b5cf6',
    accepts: ['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml'],
    actions: ['Resize', 'Compress'],
    keywords: ['image', 'resize', 'compress', 'jpg', 'jpeg', 'png', 'webp', 'photo', 'picture'],
  },
  {
    slug: '/color-tools',
    name: 'Color Picker & Palette Generator',
    navLabel: 'Color Tools',
    icon: '🎨',
    category: 'Design & Photography',
    color: '#ec4899',
    accepts: [],
    actions: ['Pick Color', 'Generate Palette'],
    keywords: ['color', 'hex', 'rgb', 'hsl', 'hsv', 'palette', 'design', 'picker', 'complementary', 'tailwind'],
  },
  {
    slug: '/ruler',
    name: 'Screen Ruler',
    navLabel: 'Screen Ruler',
    icon: '📏',
    category: 'Design & Photography',
    color: '#06b6d4',
    accepts: [],
    actions: ['Measure'],
    keywords: ['ruler', 'measure', 'screen', 'size', 'pixels', 'cm', 'inch', 'mm'],
  },
  {
    slug: '/dpi-calculator',
    name: 'DPI / PPI Print Size Calculator',
    navLabel: 'DPI Calculator',
    icon: '🖨️',
    category: 'Design & Photography',
    color: '#06b6d4',
    accepts: [],
    actions: ['Calculate DPI'],
    keywords: ['dpi', 'ppi', 'print', 'resolution', 'pixels', 'dots per inch', 'print size'],
  },
  {
    slug: '/aspect-ratio-calculator',
    name: 'Aspect Ratio & Crop Calculator',
    navLabel: 'Aspect Ratio',
    icon: '🖼️',
    category: 'Design & Photography',
    color: '#06b6d4',
    accepts: [],
    actions: ['Calculate Ratio'],
    keywords: ['aspect ratio', 'crop', '16:9', '4:3', '1:1', 'dimensions', 'frame', 'portrait', 'landscape'],
  },
  {
    slug: '/regex-tester',
    name: 'Regex Tester & Cheatsheet',
    navLabel: 'Regex Tester',
    icon: '⚡',
    category: 'Developer Tools',
    color: '#eab308',
    accepts: ['text/plain'],
    actions: ['Test Pattern'],
    keywords: ['regex', 'regexp', 'pattern', 'match', 'test', 'expression', 'string', 'replace'],
  },
  {
    slug: '/cron-expression-builder',
    name: 'Cron Expression Builder',
    navLabel: 'Cron Builder',
    icon: '⏰',
    category: 'Developer Tools',
    color: '#eab308',
    accepts: [],
    actions: ['Build Cron'],
    keywords: ['cron', 'schedule', 'expression', 'job', 'task', 'interval', 'timing'],
  },
  {
    slug: '/data-converter',
    name: 'JSON ⇄ CSV ⇄ YAML Converter',
    navLabel: 'Data Converter',
    icon: '🔁',
    category: 'Developer Tools',
    color: '#eab308',
    accepts: ['application/json', 'text/csv', 'text/plain'],
    actions: ['Convert'],
    keywords: ['json', 'csv', 'yaml', 'convert', 'data', 'format', 'transform', 'parse'],
  },
  {
    slug: '/qr-code-generator',
    name: 'QR Code Generator',
    navLabel: 'QR Code Generator',
    icon: '📱',
    category: 'Developer Tools',
    color: '#eab308',
    accepts: [],
    actions: ['Generate QR'],
    keywords: ['qr', 'qrcode', 'barcode', 'link', 'wifi', 'contact', 'vcard', 'url'],
  },
  {
    slug: '/password-checker',
    name: 'Password Strength Checker',
    navLabel: 'Password Checker',
    icon: '🔒',
    category: 'Security & Health',
    color: '#10b981',
    accepts: [],
    actions: ['Check Strength'],
    keywords: ['password', 'strength', 'security', 'entropy', 'crack', 'safe', 'hash'],
  },
  {
    slug: '/calorie-calculator',
    name: 'Calorie Calculator & Food Log',
    navLabel: 'Calorie Calculator',
    icon: '🍽️',
    category: 'Security & Health',
    color: '#10b981',
    accepts: [],
    actions: ['Calculate TDEE'],
    keywords: ['calorie', 'tdee', 'macro', 'food', 'diet', 'bmr', 'nutrition', 'weight loss'],
  },
  {
    slug: '/pregnancy-calculator',
    name: 'Pregnancy Due Date Calculator',
    navLabel: 'Pregnancy Calculator',
    icon: '🤰',
    category: 'Security & Health',
    color: '#10b981',
    accepts: [],
    actions: ['Calculate Due Date'],
    keywords: ['pregnancy', 'due date', 'ovulation', 'fertile', 'baby', 'lmp', 'weeks'],
  },
  {
    slug: '/unit-converter',
    name: 'Unit Converter',
    navLabel: 'Unit Converter',
    icon: '📐',
    category: 'Utility Tools',
    color: '#a78bfa',
    accepts: [],
    actions: ['Convert Units'],
    keywords: ['unit', 'convert', 'length', 'weight', 'temperature', 'metric', 'imperial', 'km', 'miles', 'celsius', 'fahrenheit'],
  },
]

// All unique categories in display order
export const TOOL_CATEGORIES = [
  'All',
  'Design & Photography',
  'Developer Tools',
  'PDF Tools',
  'Security & Health',
  'Utility Tools',
]

// Find tools that accept a given MIME type
export function findToolsForMime(mime, ext) {
  return WORKSPACE_TOOLS.filter((t) =>
    t.accepts.some((a) => a === mime || (ext && a.includes(ext)))
  )
}
