// Approximate values per 100g (or 100ml for drinks), based on typical USDA
// reference figures. sliceG = grams per slice (food-specific).
// pieceG = grams per piece (food-specific).
export const FOODS = [
  // ─── Fruits ───────────────────────────────────────────────────
  { name: 'Banana', kcal: 89, protein: 1.1, carbs: 23, fat: 0.3, serving: '1 medium ≈ 118g', sliceG: 30, pieceG: 118 },
  { name: 'Apple', kcal: 52, protein: 0.3, carbs: 14, fat: 0.2, serving: '1 medium ≈ 182g', sliceG: 25, pieceG: 182 },
  { name: 'Orange', kcal: 47, protein: 0.9, carbs: 12, fat: 0.1, serving: '1 medium ≈ 131g', sliceG: 22, pieceG: 131 },
  { name: 'Mango', kcal: 60, protein: 0.8, carbs: 15, fat: 0.4, serving: '1 cup diced ≈ 165g', sliceG: 30, pieceG: 200 },
  { name: 'Grapes', kcal: 69, protein: 0.7, carbs: 18, fat: 0.2, serving: '1 cup ≈ 151g', sliceG: 5, pieceG: 5 },
  { name: 'Strawberries', kcal: 32, protein: 0.7, carbs: 7.7, fat: 0.3, serving: '1 cup ≈ 152g', sliceG: 12, pieceG: 18 },
  { name: 'Watermelon', kcal: 30, protein: 0.6, carbs: 8, fat: 0.2, serving: '1 cup diced ≈ 152g', sliceG: 280, pieceG: 280 },
  { name: 'Pineapple', kcal: 50, protein: 0.5, carbs: 13, fat: 0.1, serving: '1 cup ≈ 165g', sliceG: 84, pieceG: 905 },
  { name: 'Avocado', kcal: 160, protein: 2, carbs: 8.5, fat: 14.7, serving: '1 medium ≈ 150g', sliceG: 30, pieceG: 150 },
  { name: 'Papaya', kcal: 43, protein: 0.5, carbs: 11, fat: 0.3, serving: '1 cup diced ≈ 145g', sliceG: 40, pieceG: 800 },
  { name: 'Guava', kcal: 68, protein: 2.6, carbs: 14, fat: 1, serving: '1 medium ≈ 90g', sliceG: 20, pieceG: 90 },
  { name: 'Kiwi', kcal: 61, protein: 1.1, carbs: 15, fat: 0.5, serving: '1 medium ≈ 76g', sliceG: 19, pieceG: 76 },
  { name: 'Pomegranate', kcal: 83, protein: 1.7, carbs: 19, fat: 1.2, serving: '1 medium ≈ 282g', sliceG: null, pieceG: 282 },
  { name: 'Pear', kcal: 57, protein: 0.4, carbs: 15, fat: 0.1, serving: '1 medium ≈ 178g', sliceG: 30, pieceG: 178 },
  { name: 'Peach', kcal: 39, protein: 0.9, carbs: 10, fat: 0.3, serving: '1 medium ≈ 150g', sliceG: 25, pieceG: 150 },
  { name: 'Blueberries', kcal: 57, protein: 0.7, carbs: 14, fat: 0.3, serving: '1 cup ≈ 148g', sliceG: 2, pieceG: 2 },
  { name: 'Raspberries', kcal: 52, protein: 1.2, carbs: 12, fat: 0.7, serving: '1 cup ≈ 123g', sliceG: 4, pieceG: 4 },
  { name: 'Lemon', kcal: 29, protein: 1.1, carbs: 9.3, fat: 0.3, serving: '1 medium ≈ 58g', sliceG: 8, pieceG: 58 },
  { name: 'Coconut (fresh)', kcal: 354, protein: 3.3, carbs: 15, fat: 33, serving: '1 cup shredded ≈ 80g', sliceG: null, pieceG: null },
  { name: 'Dates', kcal: 282, protein: 2.5, carbs: 75, fat: 0.4, serving: '1 date ≈ 24g', sliceG: null, pieceG: 24 },

  // ─── Vegetables ───────────────────────────────────────────────
  { name: 'Broccoli', kcal: 34, protein: 2.8, carbs: 7, fat: 0.4, serving: '1 cup chopped ≈ 91g', sliceG: null, pieceG: null },
  { name: 'Spinach', kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4, serving: '1 cup ≈ 30g', sliceG: null, pieceG: null },
  { name: 'Carrot', kcal: 41, protein: 0.9, carbs: 10, fat: 0.2, serving: '1 medium ≈ 61g', sliceG: 10, pieceG: 61 },
  { name: 'Tomato', kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2, serving: '1 medium ≈ 123g', sliceG: 20, pieceG: 123 },
  { name: 'Cucumber', kcal: 15, protein: 0.7, carbs: 3.6, fat: 0.1, serving: '1 cup sliced ≈ 104g', sliceG: 10, pieceG: 300 },
  { name: 'Onion', kcal: 40, protein: 1.1, carbs: 9.3, fat: 0.1, serving: '1 medium ≈ 110g', sliceG: 15, pieceG: 110 },
  { name: 'Potato (boiled)', kcal: 87, protein: 1.9, carbs: 20, fat: 0.1, serving: '1 medium ≈ 173g', sliceG: 50, pieceG: 173 },
  { name: 'Sweet potato (baked)', kcal: 90, protein: 2, carbs: 21, fat: 0.2, serving: '1 medium ≈ 114g', sliceG: 40, pieceG: 114 },
  { name: 'Cauliflower', kcal: 25, protein: 2, carbs: 5, fat: 0.3, serving: '1 cup chopped ≈ 107g', sliceG: null, pieceG: null },
  { name: 'Bell pepper', kcal: 31, protein: 1, carbs: 6, fat: 0.3, serving: '1 medium ≈ 119g', sliceG: 20, pieceG: 119 },
  { name: 'Cabbage', kcal: 25, protein: 1.3, carbs: 6, fat: 0.1, serving: '1 cup shredded ≈ 89g', sliceG: null, pieceG: null },
  { name: 'Eggplant', kcal: 25, protein: 1, carbs: 6, fat: 0.2, serving: '1 cup cubed ≈ 99g', sliceG: 40, pieceG: 500 },
  { name: 'Zucchini', kcal: 17, protein: 1.2, carbs: 3.1, fat: 0.3, serving: '1 cup sliced ≈ 113g', sliceG: 15, pieceG: 300 },
  { name: 'Mushrooms', kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.3, serving: '1 cup ≈ 96g', sliceG: 10, pieceG: 18 },
  { name: 'Green beans', kcal: 31, protein: 1.8, carbs: 7, fat: 0.2, serving: '1 cup ≈ 100g', sliceG: null, pieceG: 7 },
  { name: 'Peas (green)', kcal: 81, protein: 5.4, carbs: 14, fat: 0.4, serving: '1 cup ≈ 145g', sliceG: null, pieceG: null },
  { name: 'Corn', kcal: 86, protein: 3.3, carbs: 19, fat: 1.4, serving: '1 ear ≈ 103g', sliceG: null, pieceG: 103 },
  { name: 'Celery', kcal: 16, protein: 0.7, carbs: 3, fat: 0.2, serving: '1 stalk ≈ 40g', sliceG: 8, pieceG: 40 },
  { name: 'Garlic', kcal: 149, protein: 6.4, carbs: 33, fat: 0.5, serving: '1 clove ≈ 3g', sliceG: null, pieceG: 3 },
  { name: 'Ginger', kcal: 80, protein: 1.8, carbs: 18, fat: 0.8, serving: '1 tsp ≈ 2g', sliceG: null, pieceG: null },
  { name: 'Beets', kcal: 43, protein: 1.6, carbs: 10, fat: 0.2, serving: '1 cup sliced ≈ 136g', sliceG: 20, pieceG: 82 },
  { name: 'Asparagus', kcal: 20, protein: 2.2, carbs: 3.9, fat: 0.1, serving: '5 spears ≈ 75g', sliceG: null, pieceG: 15 },

  // ─── Grains & Starches ─────────────────────────────────────────
  { name: 'White rice (cooked)', kcal: 130, protein: 2.7, carbs: 28, fat: 0.3, serving: '1 cup ≈ 158g', sliceG: null, pieceG: null },
  { name: 'Brown rice (cooked)', kcal: 112, protein: 2.6, carbs: 24, fat: 0.9, serving: '1 cup ≈ 195g', sliceG: null, pieceG: null },
  { name: 'Quinoa (cooked)', kcal: 120, protein: 4.4, carbs: 21, fat: 1.9, serving: '1 cup ≈ 185g', sliceG: null, pieceG: null },
  { name: 'Pasta (cooked)', kcal: 131, protein: 5, carbs: 25, fat: 1.1, serving: '1 cup ≈ 140g', sliceG: null, pieceG: null },
  { name: 'Oats (dry)', kcal: 389, protein: 17, carbs: 66, fat: 7, serving: '1/2 cup ≈ 40g', sliceG: null, pieceG: null },
  { name: 'White bread', kcal: 265, protein: 9, carbs: 49, fat: 3.2, serving: '1 slice ≈ 30g', sliceG: 30, pieceG: 30 },
  { name: 'Whole wheat bread', kcal: 247, protein: 13, carbs: 41, fat: 3.4, serving: '1 slice ≈ 30g', sliceG: 30, pieceG: 30 },
  { name: 'Sourdough bread', kcal: 260, protein: 9, carbs: 51, fat: 1.2, serving: '1 slice ≈ 38g', sliceG: 38, pieceG: 38 },
  { name: 'Bagel', kcal: 250, protein: 10, carbs: 49, fat: 1.5, serving: '1 bagel ≈ 105g', sliceG: null, pieceG: 105 },
  { name: 'Corn flakes cereal', kcal: 357, protein: 7.5, carbs: 84, fat: 0.9, serving: '1 cup ≈ 28g', sliceG: null, pieceG: null },
  { name: 'Tortilla (flour)', kcal: 298, protein: 8, carbs: 51, fat: 7, serving: '1 tortilla ≈ 45g', sliceG: null, pieceG: 45 },
  { name: 'Chapati / Roti', kcal: 297, protein: 9.5, carbs: 57, fat: 3.8, serving: '1 roti ≈ 40g', sliceG: null, pieceG: 40 },
  { name: 'Naan bread', kcal: 317, protein: 9, carbs: 55, fat: 7, serving: '1 piece ≈ 90g', sliceG: null, pieceG: 90 },
  { name: 'Idli (steamed)', kcal: 58, protein: 2, carbs: 12, fat: 0.4, serving: '2 idlis ≈ 80g', sliceG: null, pieceG: 40 },
  { name: 'Dosa (plain)', kcal: 168, protein: 3.8, carbs: 32, fat: 3, serving: '1 dosa ≈ 100g', sliceG: null, pieceG: 100 },
  { name: 'Paratha (plain)', kcal: 302, protein: 8, carbs: 48, fat: 9.5, serving: '1 paratha ≈ 80g', sliceG: null, pieceG: 80 },
  { name: 'Couscous (cooked)', kcal: 112, protein: 3.8, carbs: 23, fat: 0.2, serving: '1 cup ≈ 157g', sliceG: null, pieceG: null },
  { name: 'Barley (cooked)', kcal: 123, protein: 2.3, carbs: 28, fat: 0.4, serving: '1 cup ≈ 157g', sliceG: null, pieceG: null },

  // ─── Protein — Meat & Poultry ──────────────────────────────────
  { name: 'Chicken breast (cooked)', kcal: 165, protein: 31, carbs: 0, fat: 3.6, serving: '1 breast ≈ 172g', sliceG: 40, pieceG: 172 },
  { name: 'Chicken thigh (cooked)', kcal: 209, protein: 26, carbs: 0, fat: 11, serving: '1 thigh ≈ 109g', sliceG: null, pieceG: 109 },
  { name: 'Beef steak (cooked)', kcal: 271, protein: 25, carbs: 0, fat: 18, serving: '100g portion', sliceG: 50, pieceG: null },
  { name: 'Ground beef (cooked)', kcal: 254, protein: 26, carbs: 0, fat: 17, serving: '100g portion', sliceG: null, pieceG: null },
  { name: 'Pork chop (cooked)', kcal: 231, protein: 27, carbs: 0, fat: 13, serving: '1 chop ≈ 145g', sliceG: null, pieceG: 145 },
  { name: 'Turkey breast (cooked)', kcal: 135, protein: 30, carbs: 0, fat: 1, serving: '100g portion', sliceG: 30, pieceG: null },
  { name: 'Lamb chop (cooked)', kcal: 294, protein: 25, carbs: 0, fat: 21, serving: '1 chop ≈ 100g', sliceG: null, pieceG: 100 },
  { name: 'Bacon (cooked)', kcal: 541, protein: 37, carbs: 1.4, fat: 42, serving: '2 strips ≈ 16g', sliceG: 8, pieceG: 8 },
  { name: 'Sausage (pork)', kcal: 378, protein: 14, carbs: 2, fat: 34, serving: '1 link ≈ 45g', sliceG: null, pieceG: 45 },
  { name: 'Hot dog', kcal: 290, protein: 11, carbs: 3, fat: 26, serving: '1 hot dog ≈ 52g', sliceG: null, pieceG: 52 },
  { name: 'Pepperoni', kcal: 494, protein: 20, carbs: 2, fat: 44, serving: '10 slices ≈ 28g', sliceG: 3, pieceG: 3 },
  { name: 'Ham (deli)', kcal: 145, protein: 19, carbs: 2, fat: 7, serving: '2 slices ≈ 60g', sliceG: 30, pieceG: 30 },

  // ─── Protein — Fish & Seafood ──────────────────────────────────
  { name: 'Salmon (cooked)', kcal: 208, protein: 22, carbs: 0, fat: 13, serving: '1 fillet ≈ 154g', sliceG: null, pieceG: 154 },
  { name: 'Tuna (canned in water)', kcal: 116, protein: 26, carbs: 0, fat: 1, serving: '1 can ≈ 142g', sliceG: null, pieceG: null },
  { name: 'Cod (cooked)', kcal: 105, protein: 23, carbs: 0, fat: 0.9, serving: '1 fillet ≈ 116g', sliceG: null, pieceG: 116 },
  { name: 'Shrimp (cooked)', kcal: 99, protein: 24, carbs: 0.2, fat: 0.3, serving: '100g ≈ ~15 medium', sliceG: null, pieceG: 7 },
  { name: 'Tilapia (cooked)', kcal: 128, protein: 26, carbs: 0, fat: 2.6, serving: '1 fillet ≈ 87g', sliceG: null, pieceG: 87 },
  { name: 'Sardines (canned)', kcal: 208, protein: 24, carbs: 0, fat: 11, serving: '1 can ≈ 92g', sliceG: null, pieceG: null },

  // ─── Protein — Eggs & Plant ────────────────────────────────────
  { name: 'Egg (whole)', kcal: 155, protein: 13, carbs: 1.1, fat: 11, serving: '1 large ≈ 50g', sliceG: null, pieceG: 50 },
  { name: 'Egg white', kcal: 52, protein: 11, carbs: 0.7, fat: 0.2, serving: '1 large white ≈ 33g', sliceG: null, pieceG: 33 },
  { name: 'Tofu (firm)', kcal: 76, protein: 8, carbs: 1.9, fat: 4.8, serving: '100g portion', sliceG: 40, pieceG: null },
  { name: 'Lentils (cooked)', kcal: 116, protein: 9, carbs: 20, fat: 0.4, serving: '1 cup ≈ 198g', sliceG: null, pieceG: null },
  { name: 'Chickpeas (cooked)', kcal: 164, protein: 9, carbs: 27, fat: 2.6, serving: '1 cup ≈ 164g', sliceG: null, pieceG: null },
  { name: 'Black beans (cooked)', kcal: 132, protein: 8.9, carbs: 24, fat: 0.5, serving: '1 cup ≈ 172g', sliceG: null, pieceG: null },
  { name: 'Kidney beans (cooked)', kcal: 127, protein: 8.7, carbs: 23, fat: 0.5, serving: '1 cup ≈ 177g', sliceG: null, pieceG: null },
  { name: 'Edamame', kcal: 121, protein: 11, carbs: 9, fat: 5.2, serving: '1 cup ≈ 155g', sliceG: null, pieceG: null },
  { name: 'Tempeh', kcal: 193, protein: 19, carbs: 9.4, fat: 11, serving: '100g portion', sliceG: 40, pieceG: null },
  { name: 'Seitan', kcal: 370, protein: 75, carbs: 14, fat: 1.9, serving: '100g portion', sliceG: null, pieceG: null },

  // ─── Dairy ─────────────────────────────────────────────────────
  { name: 'Whole milk', kcal: 61, protein: 3.2, carbs: 4.8, fat: 3.3, serving: '1 cup ≈ 244ml', sliceG: null, pieceG: null },
  { name: 'Skim milk', kcal: 35, protein: 3.4, carbs: 5, fat: 0.1, serving: '1 cup ≈ 245ml', sliceG: null, pieceG: null },
  { name: 'Greek yogurt (plain)', kcal: 59, protein: 10, carbs: 3.6, fat: 0.4, serving: '1 cup ≈ 245g', sliceG: null, pieceG: null },
  { name: 'Plain yogurt', kcal: 61, protein: 3.5, carbs: 4.7, fat: 3.3, serving: '1 cup ≈ 245g', sliceG: null, pieceG: null },
  { name: 'Cheddar cheese', kcal: 403, protein: 25, carbs: 1.3, fat: 33, serving: '1 slice ≈ 28g', sliceG: 28, pieceG: 28 },
  { name: 'Mozzarella cheese', kcal: 280, protein: 22, carbs: 2.2, fat: 22, serving: '1 oz ≈ 28g', sliceG: 28, pieceG: null },
  { name: 'Cottage cheese', kcal: 98, protein: 11, carbs: 3.4, fat: 4.3, serving: '1 cup ≈ 226g', sliceG: null, pieceG: null },
  { name: 'Butter', kcal: 717, protein: 0.9, carbs: 0.1, fat: 81, serving: '1 tbsp ≈ 14g', sliceG: null, pieceG: null },
  { name: 'Ice cream', kcal: 207, protein: 3.5, carbs: 24, fat: 11, serving: '1/2 cup ≈ 66g', sliceG: null, pieceG: null },
  { name: 'Paneer', kcal: 265, protein: 18, carbs: 3.5, fat: 20, serving: '100g portion', sliceG: 30, pieceG: null },
  { name: 'Curd / Dahi', kcal: 61, protein: 3.5, carbs: 4.7, fat: 3.3, serving: '1 cup ≈ 245g', sliceG: null, pieceG: null },
  { name: 'Cream cheese', kcal: 342, protein: 6, carbs: 4.1, fat: 34, serving: '2 tbsp ≈ 29g', sliceG: null, pieceG: null },
  { name: 'Parmesan cheese', kcal: 431, protein: 38, carbs: 4.1, fat: 29, serving: '1 tbsp ≈ 5g', sliceG: null, pieceG: null },

  // ─── Nuts, Seeds & Oils ────────────────────────────────────────
  { name: 'Almonds', kcal: 579, protein: 21, carbs: 22, fat: 50, serving: '1 oz ≈ 28g (~23 almonds)', sliceG: null, pieceG: 1 },
  { name: 'Cashews', kcal: 553, protein: 18, carbs: 30, fat: 44, serving: '1 oz ≈ 28g (~18 cashews)', sliceG: null, pieceG: 2 },
  { name: 'Walnuts', kcal: 654, protein: 15, carbs: 14, fat: 65, serving: '1 oz ≈ 28g (~14 halves)', sliceG: null, pieceG: 4 },
  { name: 'Peanuts', kcal: 567, protein: 26, carbs: 16, fat: 49, serving: '1 oz ≈ 28g (~28 peanuts)', sliceG: null, pieceG: 1 },
  { name: 'Peanut butter', kcal: 588, protein: 25, carbs: 20, fat: 50, serving: '2 tbsp ≈ 32g', sliceG: null, pieceG: null },
  { name: 'Chia seeds', kcal: 486, protein: 17, carbs: 42, fat: 31, serving: '2 tbsp ≈ 28g', sliceG: null, pieceG: null },
  { name: 'Flaxseeds', kcal: 534, protein: 18, carbs: 29, fat: 42, serving: '1 tbsp ≈ 10g', sliceG: null, pieceG: null },
  { name: 'Sunflower seeds', kcal: 584, protein: 21, carbs: 20, fat: 51, serving: '1 oz ≈ 28g', sliceG: null, pieceG: null },
  { name: 'Olive oil', kcal: 884, protein: 0, carbs: 0, fat: 100, serving: '1 tbsp ≈ 14g', sliceG: null, pieceG: null },
  { name: 'Coconut oil', kcal: 862, protein: 0, carbs: 0, fat: 100, serving: '1 tbsp ≈ 14g', sliceG: null, pieceG: null },
  { name: 'Honey', kcal: 304, protein: 0.3, carbs: 82, fat: 0, serving: '1 tbsp ≈ 21g', sliceG: null, pieceG: null },
  { name: 'Sugar (white)', kcal: 387, protein: 0, carbs: 100, fat: 0, serving: '1 tsp ≈ 4g', sliceG: null, pieceG: null },
  { name: 'Brown sugar', kcal: 380, protein: 0, carbs: 98, fat: 0, serving: '1 tsp ≈ 4g', sliceG: null, pieceG: null },

  // ─── Fast Food & Snacks ─────────────────────────────────────────
  { name: 'Pizza (cheese slice)', kcal: 266, protein: 11, carbs: 33, fat: 10, serving: '1 slice ≈ 107g', sliceG: 107, pieceG: 107 },
  { name: 'Pizza (pepperoni slice)', kcal: 298, protein: 13, carbs: 33, fat: 13, serving: '1 slice ≈ 115g', sliceG: 115, pieceG: 115 },
  { name: 'Hamburger (fast food)', kcal: 295, protein: 17, carbs: 24, fat: 14, serving: '1 burger ≈ 110g', sliceG: null, pieceG: 110 },
  { name: 'Cheeseburger (fast food)', kcal: 303, protein: 17, carbs: 24, fat: 17, serving: '1 burger ≈ 119g', sliceG: null, pieceG: 119 },
  { name: 'French fries', kcal: 312, protein: 3.4, carbs: 41, fat: 15, serving: 'small order ≈ 71g', sliceG: null, pieceG: 8 },
  { name: 'Fried chicken (piece)', kcal: 320, protein: 23, carbs: 12, fat: 21, serving: '1 piece ≈ 107g', sliceG: null, pieceG: 107 },
  { name: 'Chicken nuggets (6pc)', kcal: 312, protein: 21, carbs: 21, fat: 16, serving: '6 nuggets ≈ 102g', sliceG: null, pieceG: 17 },
  { name: 'Hot dog (with bun)', kcal: 290, protein: 11, carbs: 23, fat: 18, serving: '1 hot dog ≈ 98g', sliceG: null, pieceG: 98 },
  { name: 'Milk chocolate', kcal: 535, protein: 7.6, carbs: 59, fat: 30, serving: '1 bar ≈ 43g', sliceG: null, pieceG: 43 },
  { name: 'Dark chocolate', kcal: 546, protein: 4.9, carbs: 61, fat: 31, serving: '1 bar ≈ 43g', sliceG: null, pieceG: 43 },
  { name: 'Cookie', kcal: 488, protein: 5.4, carbs: 65, fat: 23, serving: '1 large cookie ≈ 40g', sliceG: null, pieceG: 40 },
  { name: 'Croissant', kcal: 406, protein: 8.2, carbs: 46, fat: 21, serving: '1 croissant ≈ 67g', sliceG: null, pieceG: 67 },
  { name: 'Potato chips', kcal: 536, protein: 7, carbs: 53, fat: 34, serving: '1 oz ≈ 28g', sliceG: null, pieceG: null },
  { name: 'Popcorn (air popped)', kcal: 387, protein: 13, carbs: 78, fat: 4.5, serving: '3 cups ≈ 28g', sliceG: null, pieceG: null },
  { name: 'Granola bar', kcal: 471, protein: 8, carbs: 64, fat: 20, serving: '1 bar ≈ 47g', sliceG: null, pieceG: 47 },
  { name: 'Donut (glazed)', kcal: 452, protein: 4.9, carbs: 51, fat: 25, serving: '1 donut ≈ 60g', sliceG: null, pieceG: 60 },
  { name: 'Muffin (blueberry)', kcal: 377, protein: 5.5, carbs: 55, fat: 15, serving: '1 muffin ≈ 113g', sliceG: null, pieceG: 113 },
  { name: 'Cake (chocolate)', kcal: 371, protein: 5, carbs: 52, fat: 17, serving: '1 slice ≈ 95g', sliceG: 95, pieceG: 95 },
  { name: 'Cake (vanilla)', kcal: 341, protein: 5, carbs: 51, fat: 14, serving: '1 slice ≈ 95g', sliceG: 95, pieceG: 95 },

  // ─── Indian Dishes ─────────────────────────────────────────────
  { name: 'Dal (cooked lentils)', kcal: 85, protein: 5.5, carbs: 13, fat: 1.8, serving: '1 cup ≈ 200g', sliceG: null, pieceG: null },
  { name: 'Chana masala', kcal: 130, protein: 7, carbs: 20, fat: 3.5, serving: '1 cup ≈ 200g', sliceG: null, pieceG: null },
  { name: 'Rajma (kidney beans curry)', kcal: 122, protein: 7.5, carbs: 18, fat: 3, serving: '1 cup ≈ 200g', sliceG: null, pieceG: null },
  { name: 'Palak paneer', kcal: 190, protein: 10, carbs: 8, fat: 14, serving: '1 cup ≈ 200g', sliceG: null, pieceG: null },
  { name: 'Butter chicken (murgh makhani)', kcal: 230, protein: 18, carbs: 9, fat: 14, serving: '1 cup ≈ 200g', sliceG: null, pieceG: null },
  { name: 'Biryani (chicken)', kcal: 185, protein: 11, carbs: 25, fat: 5, serving: '1 cup ≈ 200g', sliceG: null, pieceG: null },
  { name: 'Samosa', kcal: 262, protein: 4.8, carbs: 32, fat: 13, serving: '1 samosa ≈ 60g', sliceG: null, pieceG: 60 },
  { name: 'Poha (flattened rice)', kcal: 125, protein: 2.7, carbs: 27, fat: 1.1, serving: '1 cup ≈ 100g', sliceG: null, pieceG: null },
  { name: 'Upma', kcal: 181, protein: 4, carbs: 29, fat: 5.5, serving: '1 cup ≈ 150g', sliceG: null, pieceG: null },
  { name: 'Khichdi', kcal: 111, protein: 4.5, carbs: 20, fat: 1.5, serving: '1 cup ≈ 200g', sliceG: null, pieceG: null },
  { name: 'Aloo gobi', kcal: 95, protein: 2.5, carbs: 15, fat: 3, serving: '1 cup ≈ 150g', sliceG: null, pieceG: null },

  // ─── Asian Dishes ──────────────────────────────────────────────
  { name: 'Fried rice', kcal: 163, protein: 3.4, carbs: 30, fat: 2.9, serving: '1 cup ≈ 198g', sliceG: null, pieceG: null },
  { name: 'Noodles (ramen, cooked)', kcal: 138, protein: 4.7, carbs: 25, fat: 2, serving: '1 cup ≈ 212g', sliceG: null, pieceG: null },
  { name: 'Spring roll (fried)', kcal: 228, protein: 5.6, carbs: 27, fat: 11, serving: '1 roll ≈ 80g', sliceG: null, pieceG: 80 },
  { name: 'Sushi roll (8 pieces)', kcal: 200, protein: 9, carbs: 38, fat: 1.5, serving: '8 pieces ≈ 200g', sliceG: null, pieceG: 25 },
  { name: 'Miso soup', kcal: 40, protein: 2.5, carbs: 5.5, fat: 1.2, serving: '1 cup ≈ 240ml', sliceG: null, pieceG: null },
  { name: 'Pad Thai', kcal: 230, protein: 12, carbs: 34, fat: 6, serving: '1 cup ≈ 213g', sliceG: null, pieceG: null },
  { name: 'Dim sum (steamed)', kcal: 158, protein: 8, carbs: 20, fat: 5, serving: '3 pieces ≈ 75g', sliceG: null, pieceG: 25 },
  { name: 'Tofu stir fry', kcal: 120, protein: 8, carbs: 8, fat: 6, serving: '1 cup ≈ 200g', sliceG: null, pieceG: null },

  // ─── Drinks ────────────────────────────────────────────────────
  { name: 'Orange juice', kcal: 45, protein: 0.7, carbs: 10, fat: 0.2, serving: '1 cup ≈ 248ml', sliceG: null, pieceG: null },
  { name: 'Apple juice', kcal: 46, protein: 0.1, carbs: 11, fat: 0.1, serving: '1 cup ≈ 248ml', sliceG: null, pieceG: null },
  { name: 'Cola / soda', kcal: 42, protein: 0, carbs: 10.6, fat: 0, serving: '1 can ≈ 355ml', sliceG: null, pieceG: null },
  { name: 'Beer', kcal: 43, protein: 0.5, carbs: 3.6, fat: 0, serving: '1 can ≈ 355ml', sliceG: null, pieceG: null },
  { name: 'Red wine', kcal: 85, protein: 0.1, carbs: 2.6, fat: 0, serving: '1 glass ≈ 148ml', sliceG: null, pieceG: null },
  { name: 'Black coffee', kcal: 1, protein: 0.1, carbs: 0, fat: 0, serving: '1 cup ≈ 240ml', sliceG: null, pieceG: null },
  { name: 'Latte (whole milk)', kcal: 67, protein: 3.4, carbs: 7, fat: 3, serving: '12 oz ≈ 360ml', sliceG: null, pieceG: null },
  { name: 'Green tea', kcal: 2, protein: 0.2, carbs: 0.5, fat: 0, serving: '1 cup ≈ 240ml', sliceG: null, pieceG: null },
  { name: 'Protein shake (whey)', kcal: 120, protein: 25, carbs: 4, fat: 2, serving: '1 scoop ≈ 30g in 250ml water', sliceG: null, pieceG: null },
  { name: 'Sports drink (Gatorade)', kcal: 26, protein: 0, carbs: 7, fat: 0, serving: '1 cup ≈ 240ml', sliceG: null, pieceG: null },
  { name: 'Coconut water', kcal: 19, protein: 0.7, carbs: 3.7, fat: 0.2, serving: '1 cup ≈ 240ml', sliceG: null, pieceG: null },
  { name: 'Almond milk (unsweetened)', kcal: 17, protein: 0.6, carbs: 1.4, fat: 1.1, serving: '1 cup ≈ 240ml', sliceG: null, pieceG: null },
  { name: 'Lassi (sweet)', kcal: 74, protein: 3.8, carbs: 11, fat: 2, serving: '1 cup ≈ 240ml', sliceG: null, pieceG: null },
  { name: 'Mango juice', kcal: 60, protein: 0.5, carbs: 15, fat: 0.2, serving: '1 cup ≈ 250ml', sliceG: null, pieceG: null },
]

export function searchFoods(query) {
  if (!query.trim()) return []
  const q = query.toLowerCase()
  // prioritise starts-with matches, then includes
  const starts = FOODS.filter((f) => f.name.toLowerCase().startsWith(q))
  const contains = FOODS.filter((f) => !f.name.toLowerCase().startsWith(q) && f.name.toLowerCase().includes(q))
  return [...starts, ...contains].slice(0, 10)
}
